name: Rust

on:
  push:
    branches: [ "daddy" ]
  pull_request:
    branches: [ "daddy" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rewease
      run: cargo build --release --lib
